### ISSUE TITLE
cf target https://api.cloudfoundry.com error

### ISSUE THREAD

**Issue by wangzifeng** [cloudfoundry-attic/cf#1]
when run: 

cf target https://api.cloudfoundry.com

returns: 

V1 targets are no longer supported.

Not able to use login feature of CF

**Comment by tlang** [comment]
Hi. The "cf" client is only for V2 targets. You should use the "vmc" client
for V1 targets such as api.cloudfoundry.com
- Tim Lang

On Saturday, March 30, 2013, wangzifeng wrote:

> when run:
> 
> cf target https://api.cloudfoundry.com
> 
> returns:
> 
> V1 targets are no longer supported.
> 
> Not able to use login feature of CF
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudfoundry/cf/issues/1
> .

## 

Tim Lang
Product Manager, Cloud Foundry

**Comment by eliellis** [comment]
If `vmc` is deprecated shouldn't api.cloudfoundry.com be updated to work with `cf` instead? Especially since all the new documentation is referencing the use of `cf target api.cloudfoundary.com` as good-and-proper, it's pretty confusing to be following documentation that isn't representative of what's actually supposed to happen.

**Comment by tlang** [comment]
Vmc is still the correct client to use with the v1 Cloud Foundry server
components on api.cloudfoundry.com. Eventually yes api.cloudfoundry.com may
be updated to v2, at which point the correct client will be cf.

On Wednesday, April 3, 2013, Eli wrote:

> If vmc is deprecated shouldn't api.cloudfoundry.com be updated to work
> with cf instead?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudfoundry/cf/issues/1#issuecomment-15879753
> .

## 

Tim Lang
Product Manager, Cloud Foundry

**Comment by skopp** [comment]
I was instructed as well, via a core partner's docs to use `cf`. Searching online brought me here.

**Comment by dmrschmidt** [comment]
Agreed, the documentation is confusing and will be updated to correctly refer to vmc / cf.

**Comment by wendelicious** [comment]
How do I create a v2 DNS target?

**Comment by dmrschmidt** [comment]
@swps can you give a little more explanation on what you're trying to achieve? I don't think I understand what exactly you want to know. Thanks

**Comment by eliellis** [comment]
@dmrschmidt he's asking how to create a target compatible with `cf` rather than `vmc`

**Comment by laidbackgeek** [comment]
But the document of cloudfoundry show me 'cf target https://api.cloudfoundry.com', it's worry？

**Comment by tlang** [comment]
Hi. Not sure I understand the question but a few points of clarification:
- vmc is the client for talking to v1 CF targets
- cf is the client for talking to v2 CF targets
- "target" means the entire CF instance, not just a single machine. So "cf
  target https://api.cloudfoundry.com" means you're targeting a CF instance
  made up entirely of v2 components, and for which the API endpoint is
  api.cloudfoundry.com
- you "create a target compatible with cf" by installing a CF v2 instance
  (via BOSH) on your infrastructure

Not sure if that helps?
- Tim

**Comment by andypiper** [comment]
To add to @tlang's answer, the docs.cloudfoundry.com site clearly states that at the moment we are in a period of transition between v1 and v2. The docs are written for version 2, but there's a link to the older docs. As of today (May 3) our public api.cloudfoundry.com endpoint is at v1, so you should use the vmc tool to target it. If you download the Open Source components and deploy your own Cloud Foundry instance to your choice of infrastructure you can get a v2 version and use the cf tool.
