### ISSUE TITLE
can not migrate ruby project from v1 to v2

### ISSUE THREAD

**Issue by mayulu** [cloudfoundry-attic/cf#13]
My project is based ruby 1.9.3-385, it works very well in v1. When I am  migrating ti v2.

in my app folder:
$cf push
Then it shows:
-----> Using Ruby version: ruby-1.9.2

And after:

  0/1 instances: 1 down
  0/1 instances: 1 down
  0/1 instances: 1 down
  0/1 instances: 1 starting
  0/1 instances: 1 starting
  0/1 instances: 1 flapping
Application failed to start.

several times, it fails.

**Comment by cloudfoundry-attic** [comment]
Did you read over this?

http://docs.cloudfoundry.com/docs/using/deploying-apps/ruby/

**Comment by mark-rushakoff** [comment]
@drnic recently [tweeted about the Ruby version issue](https://twitter.com/drnic/status/347107403000586241) and said that you should [specify ruby in your Gemfile](http://gembundler.com/v1.2/gemfile_ruby.html) (if in fact your issue is related to the Ruby version).
