### ISSUE TITLE
cf push fails with non-ascii-file-name.war on windows

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-attic/cf#15]
When trying to push the non-ascii-file-name.war produced by vcap-java-client/cloudfoundry-client-lib into target/generated-sources it fails as follows on windows 7:

C:\code\cf_aprl_2013\vcap-java-client\cloudfoundry-client-lib\target\generated-test-resources>cf push
DL is deprecated, please use Fiddle
Name> gbe3

Instances> 1

1: 64M
2: 128M
3: 256M
4: 512M
5: 1G
6: 2G
Memory Limit> 256M

Creating gbe3... OK

1: gbe3
2: none
Subdomain> 2

1: cfapps.io
2: none
Domain> cfapps.io

Creating route .cfapps.io... FAILED
The host is taken:

1: gbe3
2: none
Subdomain> gbe4

1: cfapps.io
2: none
Domain> cfapps.io

Creating route gbe4.cfapps.io... OK
Binding gbe4.cfapps.io to gbe3... OK

Create services for application?> n

Save configuration?> n

Uploading gbe3... FAILED
Upload failed. Try again with 'cf push'.
Errno::ENOENT: No such file or directory - C:/Users/<omitted>/AppData/Local/Temp/.cf_4fc71024-b4d2-4a94-8726-ea8ceed7d88d
_files/WEB-INF/classes/faÌ?nig.properties
For more information, see ~/.cf/crash

$ cat ~/.cf/crash
Time of crash:
  2013-06-20 17:20:35 +0200

Errno::ENOENT: No such file or directory - C:/Users/<ommited>/AppData/Local/Temp/                                                                                                                                .cf_4fc71024-b4d2-4a94-8726-ea8ceed7d88d_files/WEB-INF/classes/fa▒?nig.propertie                                                                                                                                s

cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:188:in `size'
cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:188:in`block in make_fingerprints                                                                                                                                '
cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:185:in `each'
cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:185:in`make_fingerprints'
cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:144:in `determine_resources'
cfoundry-2.1.0/lib/cfoundry/upload_helpers.rb:44:in`upload'
cf-3.0.0/lib/cf/cli/app/push.rb:82:in `block in upload_app'
interact-0.5.2/lib/interact/progress.rb:98:in`with_progress'
cf-3.0.0/lib/cf/cli/app/push.rb:81:in `upload_app'
cf-3.0.0/lib/cf/cli/app/push.rb:65:in`setup_new_app'
cf-3.0.0/lib/cf/cli/app/push.rb:48:in `push'
mothership-0.5.1/lib/mothership/base.rb:66:in`run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
cf-3.0.0/lib/manifests/plugin.rb:137:in`call'
cf-3.0.0/lib/manifests/plugin.rb:137:in `block in create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in`with_filters'
cf-3.0.0/lib/manifests/plugin.rb:135:in `create_and_save_manifest'
cf-3.0.0/lib/manifests/plugin.rb:75:in`wrap_push'
cf-3.0.0/lib/manifests/plugin.rb:27:in `block in <class:ManifestsPlugin>'
mothership-0.5.1/lib/mothership/command.rb:82:in`instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in`instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in`execute'
cf-3.0.0/lib/cf/cli.rb:156:in `block (2 levels) in execute'
cf-3.0.0/lib/cf/cli.rb:167:in`save_token_if_it_changes'
cf-3.0.0/lib/cf/cli.rb:155:in `block in execute'
cf-3.0.0/lib/cf/cli.rb:101:in`wrap_errors'
cf-3.0.0/lib/cf/cli.rb:151:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in`start'
cf-3.0.0/bin/cf:13:in `<top (required)>'
C:/RubyHome/bin/cf:23:in`load'
C:/RubyHome/bin/cf:23:in `<main>'

**Comment by jfoley** [comment]
@tlang - can you comment on this?

@aramprice / @jfoley

**Comment by tlang** [comment]
Thanks for the issue info gberche-orange and sorry for the delay in response.

Looks like we won't be fixing this right away due to other priorities, but we would welcome a Pull Request if anyone feels up for it.

Possible work-around: use an ascii war file name and/or properties file name?
- Tim
