### ISSUE TITLE
target --ask-space sorta works then pukes

### ISSUE THREAD

**Issue by kushmerick** [cloudfoundry-attic/cf#16]
$ cf target --ask-space
1: coke
2: vmware
Organization> 1

Switching to organization coke... OK
NoMethodError: undefined method `ask_space' for #CF::Start::Target:0x000000028b18a0
For more information, see ~/.cf/crash

$ gem list | grep cf
admin-cf-plugin (3.0.0)
cf (2.1.0)
cf-uaa-lib (1.3.10)
cfoundry (2.1.0)

**Comment by tlang** [comment]
Thanks for this.

"--ask-space" is being removed as a flag, and "target -s [no args]" is in the process of being made more interactive. In the mean-time you have to use
cf spaces [to get list of spaces, and then...]
cf target -s [spacename]   [to switch to a specific space]
- Tim
