### ISSUE TITLE
Plugin dependency issues

### ISSUE THREAD

**Issue by michalrames** [cloudfoundry-attic/cf#17]
Following warnings / errors are displayed when running cf from windows:

```
Failed to load manifests-cf-plugin:
  Unable to activate manifests-cf-plugin-0.7.0, because cfoundry-2.1.1 conflicts with cfoundry (~> 0.6.0)

You may need to update or remove this plugin.

Failed to load tunnel-cf-plugin:
  Unable to activate tunnel-cf-plugin-0.3.0, because cfoundry-2.1.1 conflicts with cfoundry (~> 0.6.0)

You may need to update or remove this plugin.
```

I cannot tell whether there is any impact.

**Comment by dmrschmidt** [comment]
Those plugins have been merged into core cf and can safely be removed using `gem uninstall manifests-cf-plugin` and `gem uninstall tunnel-cf-plugin`. Please make sure you have the latest version of cf (3.0.0) installed as well.
