### ISSUE TITLE
cf CLI fails when used through http proxy

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-attic/cf#20]
On windows, it is necessary to define the HTTP_PROXY and HTTPS_PROXY variable and use ruby 2.0 to be able to login to the UAA.

Seems there are other issues on Ubuntu.

In addition, there are issues with app starting, even with this workaround

See details at https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/2hyjsfQOEjQ

**Comment by jfoley** [comment]
@tlang - would you mind commenting on this?

@aramprice / @jfoley

**Comment by tlang** [comment]
The bug with the HTTP_PROXY and HTTPS_PROXY cf flags has been fixed with versions of cf 5.2.0+.
