### ISSUE TITLE
cf users does not display usernames

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-attic/cf#22]
when i request the user list on my local cf i get

```
Getting users... OK
:
  admin?: true

:
  admin?: true

:
  admin?: true

:
  admin?: false
```

and i don't know it this is a bug in the cf plugin or in one of the cfv2 components

**Comment by ramonskie** [comment]
see also https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/HfwytX7QhnQ

**Comment by jfoley** [comment]
@ramonskie - Is this still an issue?

/cc @tlang 

@aramprice / @jfoley

**Comment by ramonskie** [comment]
no this issue has been resolved with the latest cloud_controller
