### ISSUE TITLE
cf should list available buildpacks

### ISSUE THREAD

**Issue by mreider** [cloudfoundry-attic/cf#25]
There should be a feature to list available buildpacks such as 'cf buildpacks' or the like.

**Comment by mreider** [comment]
For 'internal' use - I created a tracker comment here: https://www.pivotaltracker.com/story/show/47105249

**Comment by andypiper** [comment]
:+1:

**Comment by jfoley** [comment]
@tlang - if this is indeed in your backlog, could you give a rough estimate of how far away it is to being delivered? If its not something that is going to happen, please close this issue.

@aramprice / @jfoley

**Comment by jfoley** [comment]
Looks like this is something we would like to do but won't be getting to anytime soon, closing. If anyone wants to submit a PR to make this happen it would be appreciated.

@aramprice / @jfoley
