### ISSUE TITLE
`cf diff` is unknown command

### ISSUE THREAD

**Issue by scothis** [cloudfoundry-attic/cf#27]
`cf push` suggests looking at manifest differences using `cf diff`, but there is no `cf diff` command.

```
$ cf push
Using manifest file manifest.yml

Not applying manifest changes without --reset
See `cf diff` for more details.

<snip>

$ cf diff
Unknown command 'diff'. See 'help' for available commands.

$ cf -v
cf 4.1.1
```

**Comment by andypiper** [comment]
I think this is a known issue in the tracker, but thanks for pointing it out - I've seen this too.

**Comment by jfoley** [comment]
@tlang - Would you mind commenting?

@aramprice / @jfoley

**Comment by CardboardMechanic** [comment]
This reference will be removed in the next release of cf. We may add more helper text in the future.
