### ISSUE TITLE
Nginx 504 Error when pushing apps with cf 4.2.8

### ISSUE THREAD

**Issue by julweber** [cloudfoundry-attic/cf#37]
When upgrading cf to the latest version we encounter some Nginx errors while deploying applications on our anynines cf installation.

This is our test case (Rails App, Ruby 1.9) and the resulting http response:

$ cf push
Name> testara

Instances> 1

1: 128M
2: 256M
3: 512M
4: 1G
Memory Limit> 256M

Creating testara... OK

1: testara
2: none
Subdomain> testara

1: de.a9sapp.eu
2: none
Domain> de.a9sapp.eu

Creating route testara.de.a9sapp.eu... OK
Binding testara.de.a9sapp.eu to testara... OK

Create services for application?> n

Save configuration?> n

Uploading testara... OK
Preparing to start testara... FAILED
CFoundry::BadResponse: 504: <!DOCTYPE html>
<html>
<head>
<title>Error</title>

<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>

</head>
<body>

<h1>An error occurred.</h1>

<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>

<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>

<p><em>Faithfully yours, nginx.</em></p>

</body>
</html>

cat ~/.cf/crash # for more details
visitor-73-0:/Users/user/rubydev/anynines/test_apps/simple_rails_app
$ cat ~/.cf/crash
Time of crash:
  2013-08-01 11:37:53 +0200

CFoundry::BadResponse: 504: <!DOCTYPE html>
<html>
<head>
<title>Error</title>

<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>

</head>
<body>

<h1>An error occurred.</h1>

<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>

<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>

<p><em>Faithfully yours, nginx.</em></p>

</body>
</html>

<<<
REQUEST: PUT https://api.de.a9s.eu/v2/apps/2f02bb81-20d8-408a-a96b-e79806931745
REQUEST_HEADERS:
  Authorization : [PRIVATE DATA HIDDEN]
  Content-Length : 34
  Content-Type : application/json
REQUEST_BODY: {"console":true,"state":"STARTED"}
RESPONSE: [504]
RESPONSE_HEADERS:
  connection : keep-alive
  content-length : 537
  content-type : text/html
  date : Thu, 01 Aug 2013 09:37:51 GMT
  etag : "5187948a-219"
  server : nginx/1.4.1
RESPONSE_BODY:
<!DOCTYPE html>
<html>
<head>
<title>Error</title>

<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>

</head>
<body>

<h1>An error occurred.</h1>

<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>

<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>

<p><em>Faithfully yours, nginx.</em></p>

</body>
</html>

cfoundry-4.0.3/lib/cfoundry/baseclient.rb:178:in `handle_error_response'
cfoundry-4.0.3/lib/cfoundry/baseclient.rb:146:in`handle_response'
cfoundry-4.0.3/lib/cfoundry/baseclient.rb:87:in `request'
cfoundry-4.0.3/lib/cfoundry/baseclient.rb:76:in`put'
cfoundry-4.0.3/lib/cfoundry/v2/base.rb:65:in `update_app'
cfoundry-4.0.3/lib/cfoundry/v2/app.rb:152:in`update!'
cfoundry-4.0.3/lib/cfoundry/v2/app.rb:142:in `start!'
cf-4.2.8/lib/cf/cli/app/start.rb:43:in`block in start_app'
interact-0.5.2/lib/interact/progress.rb:98:in `with_progress'
cf-4.2.8/lib/cf/cli/app/start.rb:42:in`start_app'
cf-4.2.8/lib/cf/cli/app/start.rb:27:in `block in start'
cf-4.2.8/lib/cf/spacing.rb:40:in`block in spaced'
cf-4.2.8/lib/cf/spacing.rb:38:in `each'
cf-4.2.8/lib/cf/spacing.rb:38:in`spaced'
cf-4.2.8/lib/cf/cli/app/start.rb:17:in `start'
mothership-0.5.1/lib/mothership/base.rb:66:in`run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
cf-4.2.8/lib/manifests/plugin.rb:36:in`call'
cf-4.2.8/lib/manifests/plugin.rb:36:in `wrap_with_optional_name'
cf-4.2.8/lib/manifests/plugin.rb:11:in`block in default_to_app_from_manifest'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in`block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in`invoke'
mothership-0.5.1/lib/mothership/base.rb:73:in `invoke'
cf-4.2.8/lib/cf/cli/app/push/create.rb:91:in`start_app'
cf-4.2.8/lib/cf/cli/app/push.rb:66:in `setup_new_app'
cf-4.2.8/lib/cf/cli/app/push.rb:48:in`push'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in`block in invoke'
cf-4.2.8/lib/manifests/plugin.rb:135:in `call'
cf-4.2.8/lib/manifests/plugin.rb:135:in`block in create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in `with_filters'
cf-4.2.8/lib/manifests/plugin.rb:134:in`create_and_save_manifest'
cf-4.2.8/lib/manifests/plugin.rb:73:in `wrap_push'
cf-4.2.8/lib/manifests/plugin.rb:25:in`block in class:ManifestsPlugin'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in`block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in`invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-4.2.8/lib/cf/cli.rb:190:in`block (2 levels) in execute'
cf-4.2.8/lib/cf/cli.rb:201:in `save_token_if_it_changes'
cf-4.2.8/lib/cf/cli.rb:189:in`block in execute'
cf-4.2.8/lib/cf/cli.rb:125:in `wrap_errors'
cf-4.2.8/lib/cf/cli.rb:185:in`execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-4.2.8/bin/cf:13:in`<top (required)>'
ruby-1.9.3-p392@simple-cf-v2-deploy/bin/cf:19:in `load'
ruby-1.9.3-p392@simple-cf-v2-deploy/bin/cf:19:in`<main>'
ruby-1.9.3-p392@simple-cf-v2-deploy/bin/ruby_noexec_wrapper:14:in `eval'
ruby-1.9.3-p392@simple-cf-v2-deploy/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by julweber** [comment]
Deployments using cf version 4.2.0 are still running fine

**Comment by julweber** [comment]
The problem exists for all cf gem versions > 4.2.3 . Are there any server parameters that have to be configured to prevent the nginx timeouts?

**Comment by jfoley** [comment]
@tlang - this seems like a bug, can you comment?

@aramprice / @jfoley

**Comment by julweber** [comment]
We found out that this was caused by a gateway timeout when synchronous deployments exceeded the staging timeout. So increasing the staging timeout within the CC settings solved this issue for us.
