### ISSUE TITLE
cf should fail to install or report error when run on unsupported ruby

### ISSUE THREAD

**Issue by jgfoster** [cloudfoundry-attic/cf#39]
So it mostly (but not completely) works on a brand new Mac OS X 10.8 (Mountain Lion comes with ruby 1.8.7-p358)?

**Comment by andypiper** [comment]
I believe it requires 1.9.x minimum. I always install rvm on OS X first.

**Comment by tlang** [comment]
Update: we're going to cut a new cf gem in a few days that will show an error if running < ruby 1.9.3

**Comment by CardboardMechanic** [comment]
Done. Minimum Ruby version is 1.9.3. you may also want to update your rubygems to latest if you get an error about modifying a frozen string:
gem update --system
