### ISSUE TITLE
Login failed using cf, but using vmc success

### ISSUE THREAD

**Issue by hendrysuwanda** [cloudfoundry-attic/cf#4]
Steps - Steps I did:
1. cf target api.cloudfoundry.com
2. cf login -t

log that appears when I enter the password:

---

<<<
Email> suwanda.hendry@gmail.com

Password> *******************

Authenticating--->
request: post https://uaa.cloudfoundry.com/oauth/token
headers: {"content-type"=>"application/x-www-form-urlencoded;charset=utf-8", "accept"=>"application/json;charset=utf-8", "authorization"=>"Basic Y2Y6"}
body: grant_type=password&username=suwanda.hendry%40gmail.com&password=*******************
.  <---
response: 401
headers: {"server"=>"Apache-Coyote/1.1", "www-authenticate"=>"Basic realm=\"UAA/client\", error=\"unauthorized\", error_description=\"No client with requested id: cf\"", "cache-control"=>"no-store", "content-type"=>"application/json;charset=utf-8", "date"=>"Sun, 19 May 2013 08:01:52 GMT", "transfer-encoding"=>"chunked", "connection"=>"close"}
body: {"error":"unauthorized","error_description":"No client with requested id: cf"}
--->
request: post https://uaa.cloudfoundry.com/oauth/authorize?client_id=cf&response_type=token&redirect_uri=https%3A%2F%2Fuaa.cloudfoundry.com%2Fredirect%2Fcf&state=6921c8bbd97f9141b5307b0309c87eac
headers: {"content-type"=>"application/x-www-form-urlencoded;charset=utf-8", "accept"=>"application/json;charset=utf-8"}
body: username=suwanda.hendry%40gmail.com&password=*******************&source=credentials
   <---
response: 401
headers: {"server"=>"Apache-Coyote/1.1", "cache-control"=>"no-cache, no-store, no-cache, no-store, max-age=0", "content-type"=>"application/json;charset=UTF-8", "date"=>"Sun, 19 May 2013 08:01:56 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT, Thu, 01 Jan 1970 00:00:00 GMT", "pragma"=>"no-cache, no-cache", "transfer-encoding"=>"chunked", "content-language"=>"en-US", "connection"=>"close"}
body: {"error":"invalid_client","error_description":"Bad client credentials"}
... FAILED

---

> cf --version
> cf 1.0.0
> 
> ruby --version
> ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]

sorry, my english is not good.

---hendry.suwanda

**Comment by dsyer** [comment]
api.cloudfoundry.com is v1, so I'm even surprised cf allows you to target it (cf is for v2 endpoints).

**Comment by hendrysuwanda** [comment]
Hi dsyer,

first of all thank you for your response.

I read of this tutorial http://docs.cloudfoundry.com/docs/using/deploying-apps/jvm/spring-getting-started.html

in the section "Deploying Your Application"

> $ Cf targets api.cloudfoundry.com
> Setting targets to https://api.cloudfoundry.com ... OK
> 
> $ Cf login
> targets: https://api.cloudfoundry.com
> 
> Email> *********
> Password> *******
> 
> Authenticating ... OK

so for v2, where the target is addressed to?

---hendry.suwanda

**Comment by skcks** [comment]
meet the same problem, try for long time ,and still could not solve it.waitting for solution~~~

**Comment by tristanguo** [comment]
Me too, having the same problem with CFoundry::Client as well.

**Comment by dmrschmidt** [comment]
As mentioned by dsyer, api.cloudfoundry.com is a v1 endpoint which is not supported by cf. Please use [vmc](https://github.com/cloudfoundry/vmc) instead. The docs for v1 are linked on the page already mentioned and you can find them here: http://cf-docs-deprecated.cloudfoundry.com/getting-started.html

v2 is currently still in development and not yet available to the public openly. It will be announced once you can use the new v2 API.

Dennis

**Comment by andypiper** [comment]
Also, since you have been using docs.cloudfoundry.com, note that every page at the top has the following statement:

```
We are in a time of transition:
You are reading V2 documentation. The V1 docs are available [here](http://cf-docs-deprecated.cloudfoundry.com/getting-started.html).
You can browse http://api.{cloudfoundry url}/info to check a Cloud Foundry version.
The CF command-line is for Cloud Foundry V2. Use VMC for Cloud Foundry V1.
```
