### ISSUE TITLE
"user-provided, via " looks like there's an error (in cf create-service)

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf#46]
The "user-provided" option looks like there's an error:

```
$ cf create-service      
1: postgresql 9.2
2: redis 2.6
3: user-provided , via 
```

This occurs on both my own CF deployment & on run.pivotal.io.

Can we change this to just be:

```
3: user-provided
```

**Comment by shalako** [comment]
I expect this will be fixed when we remove version and provider from response for several cf commands.

Currently we see this: 

$ cf create-service
1: blazemeter n/a, via blazemeter
2: cleardb n/a, via cleardb
3: cleardb-dev n/a, via cleardb
4: cloudamqp n/a, via cloudamqp
5: cloudamqp-dev n/a, via cloudamqp
6: dummy n/a, via dummy
7: dummy-dev n/a, via dummy
8: elephantsql n/a, via elephantsql
9: elephantsql-dev n/a, via elephantsql
10: loadimpact n/a, via loadimpact
11: mongolab n/a, via mongolab
12: mongolab-dev n/a, via mongolab
13: newrelic n/a, via newrelic
14: newrelic-dev n/a, via newrelic
15: rediscloud n/a, via garantiadata
16: rediscloud-dev n/a, via garantiadata
17: sendgrid n/a, via sendgrid
18: sendgrid-dev n/a, via sendgrid
19: treasuredata n/a, via treasuredata
20: user-provided , via 

We want to see this:

$ cf create-service
1: blazemeter
2: cleardb
3: cleardb-dev
4: cloudamqp
5: cloudamqp-dev
6: dummy
7: dummy-dev
8: elephantsql
9: elephantsql-dev
10: loadimpact
11: mongolab
12: mongolab-dev
13: newrelic
14: newrelic-dev
15: rediscloud
16: rediscloud-dev
17: sendgrid
18: sendgrid-dev
19: treasuredata
20: user-provided

**Comment by drnic** [comment]
Ok cool.

```
--
```

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic
