### ISSUE TITLE
Undefined method 'create_route' while setting up a tunnel

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-attic/cf#5]
While running `bundle exec cf tunnel mysql-pit` we get: `NoMethodError: undefined method 'create_route' for #<CFoundry::V2::App 'd2ca1600-1b81-46ed-881f-0d8cedd07cda'>`

`cat ~/.cf/crash`

``` bash
NoMethodError: undefined method 'create_route' for #<CFoundry::V2::App 'd2ca1600-1b81-46ed-881f-0d8cedd07cda'>

cf-d9c8a7bb663e/lib/tunnel/tunnel.rb:146:in 'push_helper'
cf-d9c8a7bb663e/lib/tunnel/tunnel.rb:87:in 'create_helper'
```

This can be traced back to the `cfoundry` gem. There is a [to_many](https://github.com/cloudfoundry/cfoundry/blob/master/lib/cfoundry/v2/app.rb#L33) relation between the app and route objects. 

For [to_one](https://github.com/cloudfoundry/cfoundry/blob/master/lib/cfoundry/v2/model_magic.rb#L214-L222) there exists `create_#{name}` method. This is not (yet) the case for `to_many` relations.

**Comment by dmrschmidt** [comment]
Yes, this is a known issue that had been introduced in a recent update to cf / cfoundry and we are currently working on creating a fix for it. We'll update this Issue here once a bugfix is released.
