### ISSUE TITLE
Two applications created in the same sub-domain get the same access URL

### ISSUE THREAD

**Issue by bg6954** [cloudfoundry-attic/cf#53]
If an application is created in a particular sub-domain and when another application is created in the same sub-domain, the original application is getting updated incorrectly.  Both applications end up having the same access URL.

$ cf push --command "node nodejsHelloworld.js"
Name> nodejsHelloworld001

Instances> 5

1: 128M
2: 256M
3: 512M
4: 1G
Memory Limit> 256M

Creating nodejsHelloworld001... OK

1: nodejsHelloworld001
2: none
Subdomain> nodejsHelloworld001

1: cf.att.io
2: none
Domain> cf.att.io

Creating route nodejsHelloworld001.cf.att.io... OK
Binding nodejsHelloworld001.cf.att.io to nodejsHelloworld001... OK

Create services for application?> n

Bind other services to application?> n

Save configuration?> n

Uploading nodejsHelloworld001... OK
Preparing to start nodejsHelloworld001... OK
Checking status of app 'nodejsHelloworld001'...
  5 of 5 instances running (5 running)
Push successful! App 'nodejsHelloworld001' available at http://nodejsHelloworld001.cf.att.io

$ curl http://nodejsHelloworld001.cf.att.io
Hello World from my Nodejs app @173pnsaaplv

$ cf push --command "node nodejsHelloworld.js"
Name> nodejsHelloworld002

Instances> 3

1: 128M
2: 256M
3: 512M
4: 1G
Memory Limit> 256M

Creating nodejsHelloworld002... OK

1: nodejsHelloworld002
2: none
Subdomain> nodejsHelloworld001

1: cf.att.io
2: none
Domain> cf.att.io

Binding nodejsHelloworld001.cf.att.io to nodejsHelloworld001... OK

Create services for application?> n

Bind other services to application?> n

Save configuration?> n

Uploading nodejsHelloworld001... OK
Preparing to start nodejsHelloworld001... OK
Checking status of app 'nodejsHelloworld001'...
  3 of 3 instances running (3 running)
Push successful! App 'nodejsHelloworld001' available at http://nodejsHelloworld001.cf.att.io

**Comment by xoebus** [comment]
What kind of behaviour would you like to see here? It appears that now you've got two apps mapped to the same subdomain just as you specified. You'll probably see 50-50 routing between nodejsHelloworld001 and nodejsHelloworld002.

**Comment by bg6954** [comment]
Looks like route gets set as sub-domain.domain.  The confusion was going with the defaults for the sub-domain which was pre-populated with the application name.  A wrong assumption was made that route was set to application-name.domain.  Thanks!
