### ISSUE TITLE
Prevent the same application name used in two different organizations in the same domain and space to overwrite the other making the last push to win.

### ISSUE THREAD

**Issue by bg6954** [cloudfoundry-attic/cf#55]
An application created in a particular domain, space and organization can be updated via the same domain and space and a different organization.  There seems to be no way in cf to prevent application overwrite between different organizations in the same domain and space.

$ /opt/app/ruby/bin/cf login --username bg6954 --password xxxxxx -o bg6954 -s development
target: https://api.cf.att.io

Authenticating... OK
Switching to organization bg6954... OK
Switching to space development... OK

$ cf push --command "node nodejsHelloworld.js"
Name> nodejsHelloworld001

Instances> 5

1: 128M
2: 256M
3: 512M
4: 1G
Memory Limit> 256M

Creating nodejsHelloworld001... OK

1: nodejsHelloworld001
2: none
Subdomain> nodejsHelloworld001

1: cf.att.io
2: none
Domain> cf.att.io

Creating route nodejsHelloworld001.cf.att.io... OK
Binding nodejsHelloworld001.cf.att.io to nodejsHelloworld001... OK

Create services for application?> n

Bind other services to application?> n

Save configuration?> n

Uploading nodejsHelloworld001... OK
Preparing to start nodejsHelloworld001... OK
Checking status of app 'nodejsHelloworld001'...
  5 of 5 instances running (5 running)
Push successful! App 'nodejsHelloworld001' available at http://nodejsHelloworld001.cf.att.io

$ curl http://nodejsHelloworld001.cf.att.io
Hello World from my Nodejs app @173pnsaaplv

---

NOW switching to a different organization (rd7869)

$ cf login --username rd7869 --password xxxxxx -o rd7869 -s development
target: https://api.cf.att.io

Authenticating... OK
Switching to organization rd7869... OK
Switching to space development... OK

$ cf push --command "node nodejsHelloworld.js"
Name> nodejsHelloworld001

Save configuration?> n

Uploading nodejsHelloworld001... OK

nodejsHelloworld001 is currently stopped, start it with 'cf start'

$ cf start nodejsHelloworld001
Preparing to start nodejsHelloworld001... OK
Checking status of app 'nodejsHelloworld001'...
  5 of 5 instances running (5 running)
Push successful! App 'nodejsHelloworld001' available at http://nodejsHelloworld001.cf.att.io

$ curl http://nodejsHelloworld001.cf.att.io
Multi-tenant test: Hello World from my Nodejs app @173pnsagdnq

NOW switching back to organization (bg6954)

$ /opt/app/ruby/bin/cf login --username bg6954 --password xxxxxx -o bg6954 -s development
target: https://api.cf.att.io

Authenticating... OK
Switching to organization bg6954... OK
Switching to space development... OK

$ curl http://nodejsHelloworld001.cf.att.io
Multi-tenant test: Hello World from my Nodejs app @173pnsa9rli

**Comment by xoebus** [comment]
@bg6954 you'd still like to get an error even if you are a developer in both orgs? Presently you only get an error if you are a developer in Org1 trying to use a URL that is in Org2 where you are not a developer.

**Comment by bg6954** [comment]
We opened this issue not knowing that the space had changed on the terminal window after a new login had occurred with a different user/org on another terminal window.  Closing this issue and opening one for the double login issue:  https://github.com/cloudfoundry/cf/issues/60
