### ISSUE TITLE
cf should be aware of and report the protocol used for app urls, http or https

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry-attic/cf#64]
When an application is successfully deployed, the user gets a message saying:
Push successful! App 'testapp1' available at http://testapp1.appdomain.com

Which comes from the following line in start.rb:
line "#{c("Push successful! App '#{app.name}' available at http://#{app.host}.#{app.domain}", :good)}"

If the app domain is configured to use ssl, this would not be true.  It may still work if you have something listening on port 80 which will redirect the request to 443 but it would be better if there were a way for cf to know how the app domain end point is configured.  Obviously this info would have to come from the cloud controller which also doesn't have that info so we would need to get that into the cloud_controller.yml too.

Maybe something like:

app_domains:
- domain: customer-app-domain1.com
  
  protocol: https
- domain: customer-app-domain2.com
  
  protocol: http

Or --- just don't tell people the url for the app at all...

Jon Price
Cloud Platform Services
Intel Corp.

**Comment by d** [comment]
Hi Jon,
  This sounds like an open-ended question that touches multiple parts of our platform. Would you like to move this discussion over to [the mailing list](https://groups.google.com/a/cloudfoundry.org/forum/#!forum/vcap-dev) ?

@d and @sbrady

**Comment by jmprice** [comment]
Moved to the mailing list.

https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/vVtoioZmomA
