### ISSUE TITLE
Tailing logs using cf

### ISSUE THREAD

**Issue by siddhuwarrier** [cloudfoundry-attic/cf#65]
Hi,

We've just deployed cf in my org and I'm using it to run a few apps (spikes atm). I could not see any way to get cf logs to tail my logs like heroku does with heroku logs --tail (https://devcenter.heroku.com/articles/logging#realtime-tail).

This isn't quite so much a bug as it is an improvement/clarification request.

Thanks,

Siddhu

**Comment by jbayer** [comment]
with the ruby cf gem, you can use the "cf tail" command.

```
$ cf help tail
Stream an app's file contents

Usage: tail APP [PATH]

Options:
      --app APP      Application to inspect the files of
      --path PATH    Path of file to stream
```

**Comment by jbayer** [comment]
By the way, the new version of cf implemented in golang will have the logs command tail by default when using the "logs" command as it is using the new loggregator functionality:

```
$ go-cf help logs
NAME:
   logs - Tail or show recent logs for an app

USAGE:
   cf logs APP

OPTIONS:
   --recent dump recent logs instead of tailing
```
