### ISSUE TITLE
When a manifest file is used the cf command line tool does not prompt for the name

### ISSUE THREAD

**Issue by pradine** [cloudfoundry-attic/cf#69]
When I have a manifest that contains just the environment variables that I want to set as follows:

---

env:
  IBM_JVM_LICENSE: L-AWON-8GALN9
  IBM_LIBERTY_LICENSE: L-JTHS-95XRL8

The cf command line tool does not prompt for the application name, even though it does prompt for other things as follows:

C:\temp\liberty\wlp\usr\servers\defaultServer\dropins>cf push --buildpack https:
//github.com/cloudfoundry/ibm-websphere-liberty-buildpack.git
Using manifest file manifest.yml

Instances> 1

1: 128M
2: 256M
3: 512M
4: 1G
Memory Limit> 3

Creating ... OK

Time of crash:
  2013-11-05 22:39:08 +0000

TypeError: can't dup NilClass

cf-5.4.3/lib/cf/cli/app/push/interactions.rb:11:in `dup'
cf-5.4.3/lib/cf/cli/app/push/interactions.rb:11:in`ask_host'
mothership-0.5.1/lib/mothership/inputs.rb:88:in `interact'
mothership-0.5.1/lib/mothership/inputs.rb:181:in`default_for'
mothership-0.5.1/lib/mothership/inputs.rb:144:in `find_in'
mothership-0.5.1/lib/mothership/inputs.rb:106:in`get'
mothership-0.5.1/lib/mothership/inputs.rb:69:in `[]'
cf-5.4.3/lib/cf/cli/app/push/create.rb:45:in`map_route'
cf-5.4.3/lib/cf/cli/app/push.rb:55:in `setup_new_app'
cf-5.4.3/lib/cf/cli/app/push.rb:48:in`push'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in`block in invoke'
cf-5.4.3/lib/manifests/plugin.rb:108:in `call'
cf-5.4.3/lib/manifests/plugin.rb:108:in`block in push_with_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in `with_filters'
cf-5.4.3/lib/manifests/plugin.rb:105:in`push_with_manifest'
cf-5.4.3/lib/manifests/plugin.rb:90:in `block in wrap_push'
cf-5.4.3/lib/cf/spacing.rb:40:in`block in spaced'
cf-5.4.3/lib/cf/spacing.rb:38:in `each'
cf-5.4.3/lib/cf/spacing.rb:38:in`spaced'
cf-5.4.3/lib/manifests/plugin.rb:89:in `wrap_push'
cf-5.4.3/lib/manifests/plugin.rb:25:in`block in class:ManifestsPlugin'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in`block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in`invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-5.4.3/lib/cf/cli.rb:195:in`block (2 levels) in execute'
cf-5.4.3/lib/cf/cli.rb:206:in `save_token_if_it_changes'
cf-5.4.3/lib/cf/cli.rb:194:in`block in execute'
cf-5.4.3/lib/cf/cli.rb:123:in `wrap_errors'
cf-5.4.3/lib/cf/cli.rb:190:in`execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-5.4.3/bin/cf:18:in`<top (required)>'
C:/opscode/chef/embedded/bin/cf:23:in `load'
C:/opscode/chef/embedded/bin/cf:23:in`<main>'

**Comment by ruthie** [comment]
Hi,

As we commented on your other issue, cf does not support manifests without certain attributes.  Go to http://docs.cloudfoundry.com/docs/using/deploying-apps/manifest.html and scroll to the bottom to see a table of attributes.  Attributes with a 'y' in the 'required' column must be in your manifest if you are using a manifest.

Best,

@ruthie @charliebevis
