### ISSUE TITLE
Changelog please

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf#7]
Can this project maintain a Changelog between version releases? They are super useful; and also make for good content when advertising on the vcap-dev list that a new gem version is released.

**Comment by andypiper** [comment]
:+1: yes please.

**Comment by tlang** [comment]
Is now on our to-do list, thanks.

**Comment by drnic** [comment]
Why did you close this?

**Comment by drnic** [comment]
Please reopen this.

**Comment by dmrschmidt** [comment]
We've added the anchorman gem to cf and cfoundry for automatic release notes creation. You can find them [here](https://github.com/cloudfoundry/cf/tree/master/release_notes) and [here](https://github.com/cloudfoundry/cfoundry/tree/master/release_notes).

**Comment by drnic** [comment]
Interesting, hadn't seen that tool before.
​
Do you think that generated file reads well and has concise info at a glance?

I'd really like use to humanise our software delivery. I'm not comfortable with the implications of product releases without human curated changelogs. Humans make and use software. Robots don't need changelogs :)

**Comment by dmrschmidt** [comment]
Personally I feel this is a good tool to document every change that has been made. It makes sure nothing is left out of the changelog. Manual work always bears the risk of forgetting something.

However using anchorman implies discipline about the commit messages. We have to ensure they contain enough context for non-core contributors to understand what happened. With improved commit messages I think the "human" aspect to the changelogs you mentioned should come automatically, would you agree?

**Comment by drnic** [comment]
## Yep good commit messages are probably the raw material.

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic
