### ISSUE TITLE
cf delete-org always throws an error and returns an exit code of 1

### ISSUE THREAD

**Issue by bg6954** [cloudfoundry-attic/cf#71]
<b>We created an organization "testorg1"</b>
<code>
$ cf create-org testorg1
Creating organization testorg1... OK
Switching to organization testorg1... OK
There are no spaces. You may want to create one with create-space.... OK
Target Information (where will apps be pushed):
  CF instance: http://ccng.cfdemo.compute.com (API version: 2)
  user: admin
  target app space: N/A (org: testorg1)
<code>

<b>We then deleted the organization that we just created</b>
<code>
$ cf delete-org testorg1 --force --recursive
Deleting organization testorg1... OK
CFoundry::OrganizationNotFound: 30003: The organization could not be found: bdc2d1ba-aac3-418a-9db5-6bfd1e528a36
<code>

<b>We now check the return code of the delete</b>
<code>
$ echo $?
1
<code>

**Comment by oppegard** [comment]
Hi bg6954, thanks for reporting this. We're no longer actively developing or fixing the ruby cli now. Instead, we're focusing our efforts on the cf v6 beta cli (rewritten in Go).

A workaround is to use the cf v6 beta (on which we verified `delete-org -f` works). Documentation and download instructions are at: http://docs.cloudfoundry.com/docs/using/managing-apps/cf/go-cli.html

~ @oppegard & @julz
