### ISSUE TITLE
"cf stats" shows wrong cpu usage. It should be multiplied by 100

### ISSUE THREAD

**Issue by libnux** [cloudfoundry-attic/cf#72]
The cpu usage value returned from CC controller is already a percentage. When display this value, it's needed to multiply this value by 100:

Modify cf/ lib/cf/cli/app/stats.rb by changing 

"#{percentage(usage[:cpu])}",

to

"#{percentage(usage[:cpu] \* 100)}",

**Comment by jbayer** [comment]
thanks for the report! bug opened in tracker, scott truitt will triage and prioritize accordingly
https://www.pivotaltracker.com/story/show/62392176

**Comment by jfmyers9** [comment]
Fixed by 99c29cd22db209a6742864504946e847e94e890e
