### ISSUE TITLE
cf push fails... "OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A"

### ISSUE THREAD

**Issue by kmayer** [cloudfoundry-attic/cf#75]
Upload failed. Try again with 'cf push'.
Time of crash:
  2013-12-27 09:52:28 -0800

OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A

Contact Ken Mayer (@pivotal) for details

**Comment by thansmann** [comment]
Hi @kmayer - is this a consistent error? 

Please run the same 'cf' command with the ' --trace' flag:

``` bash
cf push --trace 2>&1 | tee ~/cf_push_trace.txt
```

Please post ~/cf_push_trace.txt to a gist (pasting in issues is to messy :).

Also, please post the output of 

``` bash
brew list openssl
```

from your workstation.

@thansmann && @dajulia3

**Comment by dbailey** [comment]
@kmayer is this still an issue for you? If not we'd like to do some house-keeping and close the issue :)

@dbailey && @dajulia3 (Community pair)

**Comment by kmayer** [comment]
Haven't tried it since Jan 1. Might as well close it. Come upstairs and
visit the Pivotal Analytics team if you want to see where it happened.

On Mon, Jan 13, 2014 at 12:56 PM, Dakota Bailey notifications@github.comwrote:

> @kmayer https://github.com/kmayer is this still an issue for you? If
> not we'd like to do some house-keeping and close the issue :)
> 
> @dbailey https://github.com/dbailey && @dajulia3https://github.com/dajulia3
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudfoundry/cf/issues/75#issuecomment-32210418
> .

## 

ken@bitwrangler.com | (808) 722-6142 (c)

**Comment by dajulia3** [comment]
Closing the issue. Thanks for reporting it though!
