### ISSUE TITLE
cf files - only files of instance 0 are listed

### ISSUE THREAD

**Issue by soudmaijer** [cloudfoundry-attic/cf#78]
I have an app that has multiple instances running. When I use the cf files <app> command, only the files in instance 0 are shown. Is that correct?

Can I also have a look at the other instances?

**Comment by scottruitt** [comment]
Hi Stephan,

I have a story in the cf v6 backlog to enable this: https://www.pivotaltracker.com/story/show/63429454 Should be a few weeks out, but it's coming soon. 

Hope that helps.

Scott

**Comment by soudmaijer** [comment]
Hi Scott,

thanks! Also switched to cf v6, wow with a difference in speed with the ruby version. Great job.

**Comment by scottruitt** [comment]
That's great to hear, thanks!
