### ISSUE TITLE
Rake task gem:install is absent

### ISSUE THREAD

**Issue by styx** [cloudfoundry-attic/cf#8]
There is no such task in Rakefile, but it is used on installation notes.

**Comment by dmrschmidt** [comment]
Thanks for pointing that out. Do you require such task for developing cf? There are two other ways you could potentially use.
- run `./bin/cf.dev` for running the checked out code
- run `./script/install_stable_cf.sh` (which unfortunately is out of date too though and needs to be updated)

If you just want to use the very latest version of cf a `gem install cf --pre` also does the trick.

**Comment by styx** [comment]
Thanks for the response. I'm not really required in such a task. Just tried to follow steps form Readme and failed.

**Comment by dmrschmidt** [comment]
We'll make sure the readme gets updated. Thanks for letting us know!
